trigger:
- master

pool:
  name: 'my-personal-computer'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Path'
    mavenDirectory: 'E:\maven\apache-maven-3.9.5'