trigger:
- master

pool:
  name: 'my-personal-computer'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results/TEST-*.xml'

# - task: PythonScript@0
#   inputs:
#     scriptSource: 'inline'
#     script: |
#       import os
#         files=[f for f in os.listdir('$(System.DefaultWorkingDirectory)/test-results') if os.path.isfile(f)]
#         for f in files:
#           print(f)

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/test-results'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'